---
title: "Advanced R"
author: "David Gerard"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Synopsis

This website contains the teaching materials for STAT 496/696 Advanced R, taught at American 
University by [David Gerard](https://dcgerard.github.io/).

This repository contains material based upon work supported by the National Science Foundation under Grant No. [2132247](https://nsf.gov/awardsearch/showAward?AWD_ID=2132247). The opinions, findings, and conclusions or recommendations expressed are those of the author and do not necessarily reflect the views of the National Science Foundation.

# Administrative

- [Syllabus](./syllabus.html)

# Lectures

- 01 Git/GitHub
  - [Bash Basics](./01_basic_bash.html)
  - [Setting up Git and GitHub](./01_git_setup.html)
  - [Git and GitHub](./01_git_github.html)
  - [Lab 01: Bash and Git](https://github.com/advanced-r-spring-2022/lab_01_git)
- 02 R Packages
  - [R Packages](./02_packages.html)
  - [Lab 02: R Packages](https://github.com/advanced-r-spring-2022/lab_02_packages)
- 03 Best Practices
  - [Assertions and Testing](./03_testing.html)
  - [Package Checking and Continuous Integration](./03_checking.html)
  - [Coding Style](./03_style.html)
- 04 Foundations
  - [Memory](./04_memory.html)
  - [Vectors](./04_vectors.html)
  - [Subsetting](./04_subsetting.html)
  - [Control Flow](./04_controlflow.html)
  - [Functions](./04_functions.html)
  - [Environments](./04_environments.html)
- 05 Object-oriented Programming
  - [OOP Introduction](./05_oop.html)
  - [S3 Objects](./05_s3.html)
  - [S4 Objects](./05_s4.html)
  - [Lab S4](https://github.com/advanced-r-spring-2022/lab_s4)
  - [S4 and Bioconductor](./05_bioconductor.html)
- 06 Metaprogramming
  - [Brief Overview of Metaprogramming](./06_meta.html)
  - [Formulas](./06_formulas.html)
- 07 Performance/Profiling/Memory
  - [Profiling and Microbenchmarking](./07_profiling.html)
  - [Performant R Code](./07_faster.html)
- 08 C++ and Rcpp
  - [Integrating C++ and R](./08_cpp_setup.html)
  - [C++ Basics](./08_cpp_basics.html)
  - Data Types
  - Vectors / Vector Operations
  - Control Flow
  - Rcpp Sugar
- 09 Parallel Processing
  - Futures and Running R in Batch
  - Schedulers and LSF

# Final Project

- [Final project description](./ff_project_description.html)
