---
title: "R Packages"
author: "David Gerard"
date: "`r Sys.Date()`"
output:  
  html_document:
    toc: true
    toc_depth: 4
    toc_float: false
    highlight: pygments
urlcolor: "blue"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo       = TRUE, 
                      fig.align  = "center",
                      fig.height = 3, fig.width = 4)
ggplot2::theme_set(ggplot2::theme_bw() + ggplot2::theme(strip.background = ggplot2::element_rect(fill = "white")))
```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy()
```

# Learning Objectives

- Structure of an R package.
- Documenting R packages.
- Workflow for building R packages.
- Chapters 1--8 and 10 from [R Packages](https://r-pkgs.org/index.html).

# Prereqs

- Make sure you have the `{usethis}` and `{devtools}` packages installed.
    ```{r, eval = FALSE}
    if (!require("usethis")) install.packages("usethis")
    if (!require("devtools")) install.packages("devtools")
    ```

# Package Structure

- You can create a skeleton package with the `usethis::create_package()`.

# DESCRIPTION file

# Organization of R folder

# Documentation

# Workflow

